import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Wibby</title>
        <meta name="description" content="Generated by Wibby" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main + " " + inter.className}>
        <div className={styles.center}>
          <Image
            src="/wibby.svg"
            alt="Wibby Logo"
            width={180}
            height={37}
            priority
            style={{
              position: "relative",
            }}
          />
        </div>
        <div>
          <section className={styles.section_hero}>
            <h1>Every payment method in the world, always at the best price</h1>
            <h2>
              Stop switching your payment gateway. You’ve found the final one.
            </h2>
            {/* <div className={styles.section_hero__buttons}>
              <button>Try for free</button>
              <button>Watch Demo</button>
            </div> */}
          </section>
          <section className={styles.section}>
            <h3>How does it work?</h3>
            <p>
              Easy, we are not a payment gateway. We don’t even have a banking
              license. We are at SaaS, and we are automatically doing what you
              dreamt for years.
            </p>
            <div className={styles.section_how}>
              <div className={styles.section_how__row}>
                <div className={styles.section_how__col}>
                  <h4>1</h4> You send us your documentation, and this is the
                  last time you’ll ever do it.
                </div>
                <div className={styles.section_how__col}>
                  <h4>2</h4> Once we have your documents, we get you approved by
                  every PSP that works with us around the world. No worries,
                  this takes very little time and absolutely no effort on your
                  part
                </div>
                <div className={styles.section_how__col}>
                  <h4>3</h4> Whilst we are getting you approved, you install our
                  service where you need it. If there’s a plugin, install that.
                  If you need something more custom, go to town with our APIs.
                </div>
              </div>
              <div className={styles.section_how__row}>
                <div className={styles.section_how__col}>
                  <h4>4</h4> Launch! This is where we work our magic. Your
                  checkout will show the sum of all the payment methods that our
                  partner PSPs offer. Based on the country from where the
                  customer is checking out, we will show them the most relevant
                  6 payment methods. If in need of something else, they can
                  always find it by searching for it. Once the transaction is
                  sent, we automatically assign it to the PSP that has provided
                  your business with the best conditions. That way, you always
                  have the best price.
                </div>
                <div className={styles.section_how__col}>
                  <h4>5</h4> Go in your dashboard! From here, you can see all
                  the transactions, how much they costed, who processed which
                  transaction for you. You of course can see your balances, and
                  do any action that you’re thinking of right from our
                  dashboard.
                </div>
              </div>
            </div>
          </section>
          <section className={styles.section}>
            <h3>This is gonna cost a fortune</h3>
            <p>
              No, it doesn’t. We ask for 2 things, a 9,99€ monthly fee, and we
              surcharge 0,2% of the transaction to you. Remember, our service is
              always getting you the best condition on any transaction, so you
              make our cost back instantly. And you know it too.
            </p>
          </section>
          <section className={styles.section_cta}>
            <h3>Realized this is going to change the world, yet?</h3>
            <div className={styles.section_cta__content}>
            <p>
              If you feel like a big kid and you want to sign up all by yourself
              you can do it right here:
              <button className={styles.cta}>Sign up</button>
            </p>
            <p>
            If you feel like you are such a big corporation that you deserve
              speaking to a human, you can send us a request at this form. Heads
              up, we don’t give discounts. Unless you bribe us with very cool
              tickets. Then we might. Maybe. Let’s talk
            </p>
            </div>
          </section>
        </div>
        <footer>
          If this feels too good to be true, imagine our reaction when we
          realized nobody else had built something like this. We’d be very happy
          do bond over our holy sh*t moment and answer any question you have,
          just text our bot who will connect you to the right person. Cheers!
        </footer>
        {/* <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div> */}
      </main>
    </>
  );
}
