import Head from "next/head";
import Image from "next/image";
import { Heebo } from "next/font/google";
import styles from "@/styles/Home.module.css";

const heebo = Heebo({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Wibby</title>
        <meta name="description" content="Generated by Wibby" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={[styles.main, heebo.className].join(" ")}>
        <div className={styles.center}>
          <Image
            src="/wibby.svg"
            alt="Wibby Logo"
            width={180}
            height={37}
            priority
            style={{
              position: "relative",
            }}
          />
        </div>
        <div>
          <section className={styles.section_hero}>
            <h1>
              Every payment method in the world, always at the best price.
              <br></br>
              No bullsh*t
            </h1>
            <h2>
              Stop switching your payment gateway. You’ve found the final one.
            </h2>
            {/* <div className={styles.section_hero__buttons}>
              <button>Try for free</button>
              <button>Watch Demo</button>
            </div> */}
          </section>
          <section className={[styles.section, styles.window].join(" ")}>
            <h3>How does it work?</h3>
            <p>
              It{"'"}s simple. We are not a payment gateway. We don’t even have
              a banking license. We are a service connecting you to a network of
              payment providers to always offer you the most payment methods and
              the lowest cost transactions.
            </p>
            <div className={styles.section_how}>
              <div className={styles.section_how__row}>
                <div className={styles.section_how__col}>
                  <h4>1</h4> You send us your documentation, and this is the
                  last time you’ll ever do it.
                </div>
                <div className={styles.section_how__col}>
                  <h4>2</h4> Once we have your documents, we get you approved by
                  every PSP in our network. No worries, this takes very little
                  time and absolutely no effort on your part.
                </div>
                <div className={styles.section_how__col}>
                  <h4>3</h4> Install our service where you need it. If there’s a
                  plugin, install that. If you need something more custom, go to
                  town with our APIs.
                </div>
              </div>
              <div className={styles.section_how__row}>
                <div className={styles.section_how__col}>
                  <h4>4</h4> Launch! This is where we work our magic. Your
                  checkout will show the payment methods available through
                  Wibby. Once the transaction is being processed, we
                  automatically match it to the PSP that provides the best
                  price.
                </div>
                <div className={styles.section_how__col}>
                  <h4>5</h4> Go in your dashboard! From here you can manage your
                  account, see your balance and transactions, how much they
                  cost, and who processed it.
                </div>
              </div>
            </div>
          </section>
          <section className={[styles.section, styles.window].join(" ")}>
            <h3>
              Are you wondering{" "}
              <span className={styles.italic}>“does it work for me?”</span>
            </h3>
            <p>
              Yes, it does. It works for everybody. We have plugins, but our
              APIs get us wherever we need to go.
            </p>
            <Image
              className={styles.integrations}
              width={1920}
              height={500}
              src="/wibby-integrations.png"
              alt="Payment methods"
            />
          </section>
          <section className={[styles.section, styles.window].join(" ")}>
            <h3>This is gonna cost a fortune!</h3>
            <div className={styles.cost}>
              <p>
                No, it doesn’t. <br></br>
                We ask for 2 things, a 9,99€ monthly fee, and we surcharge 0,2%
                of the transaction to you. Remember, our service is always
                getting you the best condition on any transaction, so you make
                our cost back instantly. And you know it too.
              </p>
              <h4>
                9.99€/month
                <br></br>
                <span>+ 0.2% surcharge per transaction</span>
              </h4>
            </div>
          </section>
          <section className={styles.section_cta}>
            <h3>Ready to get the best payments?</h3>
            <div className={styles.section_cta__content}>
              <p>
                Our goal is to always give you the best price possible. You can
                start right here:
                <button className={[styles.cta, heebo.className].join(" ")}>
                  Sign up coming soon
                </button>
              </p>
              <p>
                If you{"'"}re a large corporation, need a custom integration, or
                need to speak to a human you can send us a request using this
                form.
              </p>
            </div>
          </section>
          <section className={styles.section + ` ` + styles.window}>
            <p>
              Imagine our excitement when we discovered this innovation! We
              would love to bond over our incredible discovery and address any
              inquiries you may have. Simply message our bot and we{"'"}ll put
              you in touch with the appropriate individual. Cheers!
            </p>
          </section>
        </div>
        <footer className={styles.footer}>
          Copyright 2023 Wibby. All rights reserved. <br></br>
        </footer>
      </main>
    </>
  );
}
